apiVersion: v1
kind: Service
metadata:
  name: clsi
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: clsi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clsi
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: clsi
    spec:
      containers:
      - name: clsi
        image: gcr.io/henry-terraform-admin/clsi
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: status
            port: 80
          periodSeconds: 5
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1



